# Generated by Django 5.0.4 on 2024-05-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomlink',
            name='verified_ips',
            field=models.CharField(default='127.0.0.1', max_length=60),
        ),
    ]
